apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app: hello-world-svc
spec:
  selector:
    app: hello-world
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80